FROM python:3.9-slim
WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app's source code
COPY . .

EXPOSE 5000

# Define the command to run the application.
CMD ["python", "app.py"]
